version: "3"

networks:
  nats:
    name: nats

services:
  nats:
    restart: always
    image: nats
    ports:
      - "4222:4222"
      - "8222:8222"
    networks: ["nats"]

  nats-jlogger:
    restart: always
    image: nats-jlogger:0.1.0
    build:
      context: .
      dockerfile: deploy/nats-jlogger/Dockerfile
    depends_on:
      - nats
    volumes:
      - ./log:/app/log
    command: ["-natsurl=host.docker.internal:4222"]